name: Steam Monitor

on:
  schedule:
    - cron: '*/10 * * * *' # Ejecutar cada 10 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    # Permisos necesarios para poder hacer commit y push de estado.json de vuelta al repositorio
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Versión actual recomendada para minimizar avisos de depreciación

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps # Instala los navegadores y dependencias del sistema operativo Linux

      - name: Run Steam Monitor
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          WEBHOOK_URLS_CHANGES: ${{ secrets.WEBHOOK_URLS_CHANGES }}
          WEBHOOK_URL_ERRORS: ${{ secrets.WEBHOOK_URL_ERRORS }}
        run: node monitor.js # Asegúrate de que coincida con el nombre de tu archivo principal (ej. monitor.js o index.js)
        
      - name: Upload Debug Screenshot
        if: failure() # Esto solo se ejecuta si el paso anterior falla
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error_screenshot.png

      - name: Commit estado.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add estado.json
          git diff --cached --quiet || (git commit -m "Update estado.json" && git push)
