name: Steam Monitor

on:
  schedule:
    - cron: '*/10 * * * *' # Se ejecuta cada 10 minutos
  workflow_dispatch: # Permite ejecutar el flujo manualmente desde GitHub

jobs:
  monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Necesario para hacer commit y push de estado.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Steam Monitor
        env:
          WEBHOOK_URLS_CHANGES: ${{ secrets.WEBHOOK_URLS_CHANGES }}
          WEBHOOK_URL_ERRORS: ${{ secrets.WEBHOOK_URL_ERRORS }}
        run: node monitor.js

      - name: Commit estado.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add estado.json
          git diff --cached --quiet || (git commit -m "Update estado.json" && git push)
